version: 0.2

phases:
  install:
    commands:
      - echo "===== INSTALL TERRAFORM ====="
      - TERRAFORM_VERSION="1.9.8"
      - curl -fsSLo terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform
      - chmod +x /usr/local/bin/terraform
      - terraform version

  build:
    commands:
      - echo "===== TERRAFORM FMT ====="
      - echo "===== CURRENT DIRECTORY ====="
      - pwd
      - echo "===== TERRAFORM FILES ====="
      - ls -la
      - terraform fmt -diff -check -recursive
      - echo "===== TERRAFORM FMT COMPLETED ====="
      - echo "===== TERRAFORM INIT ====="
      - terraform init -input=false
      - echo "===== TERRAFORM INIT COMPLETED ====="
      - echo "===== TERRAFORM VALIDATE ====="
      - terraform validate
      - echo "===== TERRAFORM VALIDATE COMPLETED ====="
      - echo "===== TERRAFORM PLAN ====="
      - terraform plan -input=false -out=tfplan
      - echo "===== TERRAFORM PLAN COMPLETED ====="

  post_build:
    commands:
      - echo "===== BUILD COMPLETED ====="
      - echo "Terraform fmt, init, validate, and plan completed successfully"